name: CI/CD Pipeline with Keploy and Dual MySQL - Anime Watch List

on:
    push:
        branches: [main]

env:
    KEPLOY_API_KEY: 681a05812921eade9b097454@all
    KEPLOY_APP_ID: ab8b3629-3582-4d21-815d-ccc9886c8cc5

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:24.0.7
                options: --privileged

        steps:
            # Step 1: Checkout code
            - name: Checkout code
              uses: actions/checkout@v4

            # Step 2: Set up Go
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21

            # Step 3: Start Docker Network and MySQL containers
            - name: Setup MySQL databases
              run: |
                  docker network create mysql-network || true

                  # Unit Test DB
                  docker run -d \
                    --name mysql-anime-watch-list-test \
                    --network mysql-network \
                    -e MYSQL_ROOT_PASSWORD=testqwerty \
                    -e MYSQL_DATABASE=test-anime-watch-list \
                    -p 5011:3306 \
                    mysql:latest

                  # Main DB
                  docker run -d \
                    --name mysql-anime-watch-list-main \
                    --network mysql-network \
                    -e MYSQL_ROOT_PASSWORD=qwerty \
                    -e MYSQL_DATABASE=anime-watch-list \
                    -p 5010:3306 \
                    mysql:latest

                  # Wait for databases to be ready
                  sleep 25

            # Step 4: Install Go dependencies
            - name: Install dependencies
              run: go mod tidy

            # Step 5: Run Unit, Integration, and API Tests
            - name: Run Go Tests
              run: go test -v -cover ./...

            # Step 6: Install Keploy
            - name: Setup Keploy
              run: |
                  curl --silent -L https://keploy.io/ent/install.sh | bash
                  echo "$HOME/.keploy/bin" >> $GITHUB_PATH

            # Step 7: Build and Run Application
            - name: Build and Run Application
              run: |
                  go build -o anime-watch-list ./cmd/server
                  ./anime-watch-list &
                  echo $! > app.pid
                  sleep 10

            # Step 8: Run Keploy Cloud Test Suite
            - name: Run Keploy Tests
              run: |
                  keploy test-suite \
                    --app=$KEPLOY_APP_ID \
                    --base-path=http://localhost:8080 \
                    --cloud

                  # Clean up
                  kill $(cat app.pid)
                  rm app.pid
