name: CI/CD Pipeline with Keploy and Dual MySQL - Anime Watch List

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:24.0.7
                options: --privileged

        steps:
            # Step 1: Checkout code
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            # Step 2: Set up Go
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21

            # Step 3: Start Docker Network
            - name: Create Docker Network
              run: |
                  docker network create mysql-network

            # Step 4: Run MySQL for Unit Tests (port 5011)
            - name: Start Unit Test DB (MySQL)
              run: |
                  docker run -d \
                    --name mysql-anime-watch-list-test \
                    --network mysql-network \
                    -e MYSQL_ROOT_PASSWORD=testqwerty \
                    -e MYSQL_DATABASE=test-anime-watch-list \
                    -p 5011:3306 \
                    mysql

            # Step 5: Run MySQL for Main App (port 5010)
            - name: Start Main DB (MySQL)
              run: |
                  docker run -d \
                    --name mysql-anime-watch-list-main \
                    --network mysql-network \
                    -e MYSQL_ROOT_PASSWORD=qwerty \
                    -e MYSQL_DATABASE=anime-watch-list \
                    -p 5010:3306 \
                    mysql

            # Step 6: Wait for MySQL to become ready
            - name: Wait for DBs
              run: sleep 25

            # Step 7: Set up environment
            - name: Install Go dependencies
              run: go mod tidy

            # Step 8: Run Unit, Integration, and API Tests
            - name: Run All Go Tests
              run: |
                  go test -v -cover ./...

            # Step 9: Install Keploy
            - name: Setup Keploy
              run: |
                  curl --silent -L https://keploy.io/ent/install.sh | bash

            # Step 10: Run Keploy Cloud Test Suite
            - name: Run Keploy Cloud Test Suite
              run: |
                  keploy test-suite \
                    --app=03d24177-315c-4ee1-a3ac-64ed0ab38567 \
                    --base-path=http://localhost:8080/books \
                    --cloud \
                    --header "KEPLOY_API_KEY: 681a05812921eade9b097454@all"
