name: CI/CD Pipeline for Book Tracker API with Keploy

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_DATABASE: anime-watch-list
            KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}

        steps:
            # Checkout the code
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            # Set up Go
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.24

            # Install dependencies
            - name: Install Go dependencies
              run: go mod tidy

            # Create a Docker network
            - name: Create MySQL Docker network
              run: docker network create mysql-network

            # Start MySQL container for UNIT tests (port 5011)
            - name: Start Unit Test DB (write DB)
              run: |
                  docker run -d \
                    --name mysql-anime-watch-list-test \
                    --network mysql-network \
                    -e MYSQL_ROOT_PASSWORD=testqwerty \
                    -e MYSQL_DATABASE=test-anime-watch-list \
                    -p 5011:3306 \
                    mysql

            # Start MySQL container for READ DB (port 5010)
            - name: Start Read DB
              run: |
                  docker run -d \
                    --name mysql-anime-watch-list-read \
                    --network mysql-network \
                    -e MYSQL_ROOT_PASSWORD=qwerty \
                    -e MYSQL_DATABASE=anime-watch-list \
                    -p 5010:3306 \
                    mysql

            # Install Keploy
            - name: Install Keploy
              run: |
                  curl --silent -L https://keploy.io/ent/install.sh | bash

            # Wait for MySQL to be ready
            - name: Wait for MySQL to be ready
              run: |
                  for i in {1..10}; do
                    docker exec mysql-anime-watch-list-test mysqladmin ping -h127.0.0.1 -uroot -ptestqwerty && break
                    sleep 5
                  done

            # Run tests (unit/integration/api)
            - name: Run Go tests
              run: |
                  go test -v ./...

            # Run Keploy test suite
            - name: Run Keploy Cloud Test Suite
              run: |
                  keploy test-suite --app=03d24177-315c-4ee1-a3ac-64ed0ab38567 --base-path=http://localhost:8080/books --cloud
