name: CI for Anime Watchlist API

on:
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.24

            - name: Install dependencies
              run: go mod download

            - name: Create Docker network
              run: docker network create mysql-network

            - name: Start test MySQL database container (port 5011)
              run: |
                  docker run -d \
                    --name mysql-anime-watch-list-test \
                    --network mysql-network \
                    -e MYSQL_ROOT_PASSWORD=testqwerty \
                    -e MYSQL_DATABASE=test-anime-watch-list \
                    -p 5011:3306 \
                    mysql

            - name: Start read-only MySQL container (port 5010)
              run: |
                  docker run -d \
                    --name mysql-anime-watch-list-read \
                    --network mysql-network \
                    -e MYSQL_ROOT_PASSWORD=qwerty \
                    -e MYSQL_DATABASE=anime-watch-list \
                    -p 5010:3306 \
                    mysql

            - name: Wait for MySQL containers to be ready
              run: |
                  echo "Waiting for MySQL on ports 5011 and 5010..."
                  for i in {1..20}; do
                    nc -zv 127.0.0.1 5011 && nc -zv 127.0.0.1 5010 && echo "Both DBs are up!" && break
                    echo "Waiting..."
                    sleep 3
                  done

            - name: Run Go tests with coverage
              run: |
                  go test -v -coverpkg=./internal/db,./internal/handlers,./internal/repository ./tests/... -coverprofile=coverage.out

            - name: Show coverage report
              run: |
                  go tool cover -func=coverage.out
